# DCE Config
# DCE Github: https://github.com/EDGRRRRs/DCE
# Plugin author: EDGRRRR
# Author Github: https://github.com/EDGRRRRs
# Helpers:
#   - ExRider111Ryan: https://github.com/RyanA3
#
# Colours can be found here: https://jd.bukkit.org/org/bukkit/ChatColor.html
# Also supports the colour characters such as &1 &2 &3 &4 &5 &6 &7...

main:
  version: 1.4.117

chat:
  chatDebug: false
  consolePrefix: '&b[DivinityEconomy v<VERSION>]&9> '
  chatPrefix: '&b[D.E]&9> '
  infoColour: 'GREEN'
  severeColour: 'RED'
  warnColour: 'YELLOW'
  debugColour: 'DARK_PURPLE'
  moneyScale: 2
  moneyPrefix: "£"
  moneySingular: "Divinity"
  moneyPlural: "Divinity's"

economy:
  minAccountBalance: 0.0
  minSendAmount: 0.01
  preferredProvider: 'DivinityEconomy'

market:
  saveTimer: 600

  enchants:
    enable: true
    baseQuantity: 1000000
    buyTax: 1.0
    sellTax: 0.9
    wholeMarketInflation: false
    dynamicPricing: true

  materials:
    enable: true
    baseQuantity: 1000000
    buyTax: 1.25
    sellTax: 1.125
    wholeMarketInflation: false
    dynamicPricing: true
    itemDamageScaling: true


commands:
  admin:
    clearBal: true
    editBal: true
    setBal: true
    reloadMaterials: true
    reloadEnchants: true
    setStock: true
    setValue: true
    eSetStock: true
    eSetValue: true
    saveMaterials: true
    saveEnchants: true

  economy:
    balance: true
    sendCash: true

  enchant:
    eBuy: true
    eInfo: true
    eSell: true
    eValue: true
    eHandValue: true

  mail:
    clearMail: true
    readMail: true

  market:
    buyItem: true
    handBuy: true
    handInfo: true
    handSell: true
    handValue: true
    info: true
    sellItem: true
    value: true

  misc:
    ping: true
    ehelp: true
