Main:
  Version: 1.18.2

Chat:
  Chat Debug: false
  Console Prefix: '&b[DivinityEconomy v<VERSION>]&9> '
  Chat Prefix: '&b[D.E]&9> '
  Info Colour: 'GREEN'
  Severe Colour: 'RED'
  Warn Colour: 'YELLOW'
  Debug Colour: 'DARK_PURPLE'
  Money Scale: 2
  Money Prefix: "£"
  Money Singular: "Divinity"
  Money Plural: "Divinity's"

Tab Completion:
  Use Fuzzy Search: true
  Fuzzy Search:
    Min Score: 70.0
    Max Results: 50

Message Ignore:
  Ignore Alias Errors: false
  Ignore Item Errors: false
  Ignore Command Registry: true

Economy:
  Min Account Balance: 0.0
  Min Send Amount: 0.01
  Preferred Provider: 'DivinityEconomy'
  Baltop Refresh Timer: 300

Market:
  Save Timer: 600

  Enchants:
    Enable: true
    Base Quantity: 1000000
    Buy Scale: 1.1
    Sell Scale: 1.0
    Whole Market Inflation: false
    Dynamic Pricing: true
    Allow Unsafe Enchants: false

  Materials:
    Enable: true
    Base Quantity: 1000000
    Buy Scale: 1.0
    Sell Scale: 0.9
    Whole Market Inflation: false
    Dynamic Pricing: true
    Item Damage Scaling: true


Commands:
  Admin:
    Clear Bal: true
    Edit Bal: true
    Set Bal: true
    Reload Materials: true
    Reload Enchants: true
    Set Stock: true
    Set Value: true
    E Set Stock: true
    E Set Value: true
    Save Materials: true
    Save Enchants: true
    Reload: true

  Economy:
    Balance: true
    Send Cash: true
    Baltop: true

  Enchant:
    E Buy: true
    E Info: true
    E Sell: true
    E Value: true
    E Hand Value: true

  Mail:
    Clear Mail: true
    Read Mail: true

  Market:
    Buy: true
    Hand Buy: true
    Hand Info: true
    Hand Sell: true
    Hand Value: true
    Info: true
    Sell: true
    Value: true
    Sell All: true
    List Items: true

  Misc:
    Ping: true
    E Help: true
