# DCE Config
# DCE Github: https://github.com/EDGRRRRs/DCE
# Plugin author: EDGRRRR
# Author Github: https://github.com/EDGRRRRs
# Other helpers:
#   - ExRider111Ryan: https://github.com/RyanA3
#
# Colours can be found here: https://jd.bukkit.org/org/bukkit/ChatColor.html
# Also supports the colour characters such as &1 &2 &3 &4 &5 &6 &7...
#
# [Config]

main:
  version: "1.0.1"

chat:
  chatDebug: false
  consolePrefix: "&b[DCE v<VERSION>] &b- "
  chatPrefix: "&b[DCE] &b- "
  infoColour: "GREEN"
  warnColour: "YELLOW"
  severeColour: "RED"
  debugColour: "DARK_PURPLE"

economy:
  enable: true
  minAccountBalance: 0.0
  minSendAmount: 0.01
  roundingDigits: 2

market:
  saveTimer: 600
  materials:
    enable: true
    baseQuantity: 1000000
    buyTax: 1.2
    sellTax: 1.0

  enchants:
    enable: true
    baseQuantity: 1000000
    buyTax: 2.0
    sellTax: 1.0

commands:
  economy:
    balance: true
    sendCash: true

  misc:
    ping: true

  admin:
    clearBal: true
    editBal: true
    setBal: true

  market:
    buyItem: true
    sellItem: true
    value: true
    info: true
    handSell: true
    handBuy: true
    handInfo: true
    handValue: true

  mail:
    readMail: true
    clearMail: true

  enchant:
    eHandSell: true
    eHandBuy: true
    eHandValue: true
    eValue: true
    eHandInfo: true
    eInfo: true
