# Main settings
#   debugMode: enables and disables debugging.
#   version: the version of the config file - do not touch!
# 
# Chat settings
#   Colours can be found here: https://jd.bukkit.org/org/bukkit/ChatColor.html
#   chatDebug: The prefix for the plugin in chat
#   prefix: The prefix seperator for the plugin in chat
#   prefixSep: The colour of the prefix
#   prefixColour: The colour of the prefix seperator
#   prefixConsole:
#     The prefix for console messages
#     Codes: 
#       %V: version of the plugin
#     infoColour: The colour of general messages
#   warnColour: The colour of warn-level errors in console and to players
#   severeColour: The colour of severe-level errors in console (mostly)
#   debugColour: The colour of debug-level messages in console - only applies if debugMode is enabled or chatDebug is enabled.
# 
# Economy
#   minSendAmount - The minimum amount of money a user can send to another users
#   roundingDigits - The level of resolution to use when rounding.
# 
# Commands
#   balance - returns the users balance
#   clearBal - #ADMIN# clears a users balance
#   editBal - #ADMIN# adds or removes cash from a users balance
#   ping - A test command
#   sendCash - lets users send cash to one another
#   setBal - #ADMIN# sets a users balance

main:
  debugMode: false
  version: "1.0.1"
chat:
  chatDebug: false
  prefix: "[DCE]"
  prefixSep: " - "
  prefixColour: "AQUA"
  prefixSepColour: "AQUA"
  prefixConsole: "[DCE v%V]"
  infoColour: "GREEN"
  warnColour: "YELLOW"
  severeColour: "RED"
  debugColour: "DARK_PURPLE"
economy:
  minSendAmount: 0.01
  roundingDigits: 2
  baseQuantity: 1000000
  tax: 1.2
commands:
  balance: true
  clearBal: true
  editBal: true
  ping: true
  sendCash: true
  setBal: true